### ISSUE TITLE
'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by walkintom** [autopkg/andrewzirkel-recipes#7]
Me again, just taking another look at the recipe after the downloading issue was resolved and I'm getting this. Any ideas at all?

```
autopkg run -vvv local.munki.Sibelius
Processing local.munki.Sibelius...
{'AUTOPKG_VERSION': '2.3.1',
 'CACHE_DIR': '/Volumes/Data/AutoPkg/Cache',
 'GIT_PATH': '/Library/Developer/CommandLineTools/usr/bin/git',
 'MUNKI_REPO': '/Volumes/Data/munki_repo',
 'MUNKI_REPO_SUBDIR': 'apps',
 'MYAVID_PASSWORD': '',
 'MYAVID_USERNAME': '',
 'NAME': 'Sibelius',
 'PARENT_RECIPES': ['/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.andrewzirkel-recipes/Sibelius/Sibelius.munki.recipe',
                    '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.andrewzirkel-recipes/Sibelius/Sibelius.pkg.recipe',
                    '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.andrewzirkel-recipes/Sibelius/Sibelius.download.recipe'],
 'RECIPE_CACHE_DIR': '/Volumes/Data/AutoPkg/Cache/local.munki.Sibelius',
 'RECIPE_DIR': '/Volumes/Data/AutoPkg/RecipeOverrides',
 'RECIPE_OVERRIDE_DIRS': ['/Volumes/Data/AutoPkg/RecipeOverrides'],
 'RECIPE_PATH': '/Volumes/Data/AutoPkg/RecipeOverrides/Sibelius.munki.recipe',
 'RECIPE_REPOS': {'/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.andrewzirkel-recipes': {'URL': 'https://github.com/autopkg/andrewzirkel-recipes.git'},
                  '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.apettinen-recipes': {'URL': 'https://github.com/autopkg/apettinen-recipes.git'},
                  '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.apizz-recipes': {'URL': 'https://github.com/autopkg/apizz-recipes.git'},
                  '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.aysiu-recipes': {'URL': 'https://github.com/autopkg/aysiu-recipes.git'},
                  '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes': {'URL': 'https://github.com/autopkg/dataJAR-recipes.git'},
                  '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.foigus-recipes': {'URL': 'https://github.com/autopkg/foigus-recipes.git'},
                  '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.grahamgilbert-recipes': {'URL': 'https://github.com/autopkg/grahamgilbert-recipes.git'},
                  '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes': {'URL': 'https://github.com/autopkg/hjuutilainen-recipes.git'},
                  '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.jessepeterson-recipes': {'URL': 'https://github.com/autopkg/jessepeterson-recipes.git'},
                  '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes': {'URL': 'https://github.com/autopkg/joshua-d-miller-recipes.git'},
                  '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.jps3-recipes': {'URL': 'https://github.com/autopkg/jps3-recipes.git'},
                  '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.keeleysam-recipes': {'URL': 'https://github.com/autopkg/keeleysam-recipes.git'},
                  '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.moofit-recipes': {'URL': 'https://github.com/autopkg/moofit-recipes.git'},
                  '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.mosen-recipes': {'URL': 'https://github.com/autopkg/mosen-recipes.git'},
                  '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.munkireport-recipes': {'URL': 'https://github.com/autopkg/munkireport-recipes.git'},
                  '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.n8felton-recipes': {'URL': 'https://github.com/autopkg/n8felton-recipes.git'},
                  '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.neilmartin83-recipes': {'URL': 'https://github.com/autopkg/neilmartin83-recipes.git'},
                  '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.novaksam-recipes': {'URL': 'https://github.com/autopkg/novaksam-recipes.git'},
                  '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.recipes': {'URL': 'https://github.com/autopkg/recipes.git'},
                  '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes': {'URL': 'https://github.com/autopkg/rtrouton-recipes.git'},
                  '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.rustymyers-recipes': {'URL': 'https://github.com/autopkg/rustymyers-recipes.git'},
                  '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.valdore86-recipes': {'URL': 'https://github.com/autopkg/valdore86-recipes.git'}},
 'RECIPE_REPO_DIR': '/Volumes/Data/AutoPkg/RecipeRepos',
 'RECIPE_SEARCH_DIRS': ['.',
                        '~/Library/AutoPkg/Recipes',
                        '/Library/AutoPkg/Recipes',
                        '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.recipes',
                        '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.hjuutilainen-recipes',
                        '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.mosen-recipes',
                        '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.grahamgilbert-recipes',
                        '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.dataJAR-recipes',
                        '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.jps3-recipes',
                        '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.aysiu-recipes',
                        '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.jessepeterson-recipes',
                        '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.joshua-d-miller-recipes',
                        '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.neilmartin83-recipes',
                        '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.apizz-recipes',
                        '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.novaksam-recipes',
                        '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.foigus-recipes',
                        '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.valdore86-recipes',
                        '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes',
                        '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.keeleysam-recipes',
                        '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.n8felton-recipes',
                        '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.apettinen-recipes',
                        '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.munkireport-recipes',
                        '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.moofit-recipes',
                        '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.rustymyers-recipes',
                        '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.andrewzirkel-recipes',
                        '/Volumes/Data/AutoPkg/RecipeOverrides',
                        '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.andrewzirkel-recipes/Sibelius',
                        '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.andrewzirkel-recipes/Sibelius',
                        '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.andrewzirkel-recipes/Sibelius',
                        '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.andrewzirkel-recipes/Sibelius',
                        '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.andrewzirkel-recipes/Sibelius',
                        '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.andrewzirkel-recipes/Sibelius',
                        '/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.andrewzirkel-recipes/Sibelius'],
 'pkginfo': {'catalogs': ['testing'],
             'category': 'Music',
             'description': '',
             'developer': 'Avid',
             'display_name': 'Sibelius',
             'name': 'Sibelius',
             'unattended_install': True,
             'unattended_uninstall': True},
 'verbose': 3}
SibeliusURLProvider
{'Input': {'password': '',
           'username': ''}}
Traceback (most recent call last):
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 626, in process
    self.main()
  File "/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.andrewzirkel-recipes/Sibelius/SibeliusURLProvider.py", line 134, in main
    self.env["url"] = self.get_url(username, password)
  File "/Volumes/Data/AutoPkg/RecipeRepos/com.github.autopkg.andrewzirkel-recipes/Sibelius/SibeliusURLProvider.py", line 112, in get_url
    PN = re.search(PN_REGEX, html).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
  File "/Library/AutoPkg/autopkglib/__init__.py", line 840, in process
    self.env = processor.process()
'NoneType' object has no attribute 'group'
Failed.
Receipt written to /Volumes/Data/AutoPkg/Cache/local.munki.Sibelius/receipts/local.munki-receipt-20220104-151459.plist

The following recipes failed:
    local.munki.Sibelius
        Error in local.munki.Sibelius: Processor: SibeliusURLProvider: Error: 'NoneType' object has no attribute 'group'

Nothing downloaded, packaged or imported.
```

**Comment by andrewzirkel** [comment]
I only have access to sibelius first in my account so I'm just guessing that you probably have the paid version and I'm guessing that this might fix it.  Otherwise I would suggest making a new avid account just for this purpose and adding sibelius first to it, which is free.

**Comment by andrewzirkel** [comment]
I got access to an account with the paid version and updated the URL Provider to handle that.  Let me know if it doesn't work.
